[package]
name = "bled-core"
version = "0.1.0"
edition = "2024"
license = "MIT"

[lints.rust]
unused_crate_dependencies = "deny"

[dependencies]
bytemuck = { version = "1.25.2", default-features = false }
defmt = { version = "1", default-features = false, optional = true }
getset = "0.1.7"
heapless = { version = "0.9", features = ["serde"] }
minicbor = "2.3.0"
minicbor-serde = "0.7.1"
nutype = { version = "0.8.0", default-features = false, features = ["derive_unchecked", "serde"] }
rgb = { version = "0.8.53", features = ["serde"] }
serde = { version = "1.0.229", default-features = false, features = ["derive"] }
serde-json-core = "0.6.0"
thiserror = { version = "2.0.20", default-features = false }
uuid = { version = "1.26.0", default-features = false }

[features]
defmt = [
  "dep:defmt",
  "heapless/defmt",
  "serde-json-core/defmt",
  "rgb/defmt-03",
]
