---
name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  formatting:
    name: Formatting
    runs-on: ubuntu-slim

    steps:
      - uses: actions/checkout@v7
      - uses: DeterminateSystems/nix-installer-action@v23

      - name: Format
        run: nix develop --command treefmt --fail-on-change

  api:
    name: API crate
    needs:
      - formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: DeterminateSystems/nix-installer-action@v23

      - name: Clippy
        run: |
          set -x
          cd ./api
          nix develop --command cargo clippy -- -Dwarnings

      - name: Tests
        run: |
          set -x
          cd ./api
          nix develop --command cargo test

  cli:
    name: CLI
    needs:
      - api
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: DeterminateSystems/nix-installer-action@v23

      - name: Clippy
        run: |
          set -x
          cd ./cli
          nix develop --command cargo clippy -- -Dwarnings

      - name: Build
        run: |
          set -x
          cd ./cli
          nix develop --command cargo build --release

  firmware:
    name: Firmware
    needs:
      - api
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: DeterminateSystems/nix-installer-action@v23

      - name: Clippy
        run: |
          set -x
          cd ./firmware
          nix develop --command just clippy

      - name: Build
        run: |
          set -x
          cd ./firmware
          nix develop --command just
